#!/bin/bash

# prevents xscreensaver from blanking/locking screen

case $1 in
	-t | --time) # time to stay awake for, in minutes
        for pid in $(pidof -x insomnia); do
            if [ $pid != $$ ]; then
                echo "[$(date)] : insomnia : Process is already running with PID $pid"
                exit 1
            fi
        done
        echo "insomnia for $2 minutes"
		n=0
		if [ $2 -eq $2 ] 2>/dev/null; then # checks if whole number and hides error message
			while [ $2 -gt $n ]; do
				xscreensaver-command -deactivate > /dev/null
				sleep 59
				n=$(($n+1))
			done
      xscreensaver-command -activate > /dev/null
			exit
		else
			while true; do
				xscreensaver-command -deactivate > /dev/null
				sleep 59
			done
		fi
		;;
	-f | --forever) # never sleeps
        for pid in $(pidof -x insomnia); do
            if [ $pid != $$ ]; then
                echo "[$(date)] : insomnia : Process is already running with PID $pid"
                exit 1
            fi
        done
        echo "insomnia forever"
		while true; do
			xscreensaver-command -deactivate > /dev/null
			sleep 59
		done
		;;
	-q | --quit) # activates screensaver
        xscreensaver-command -activate > /dev/null
        # optional, to turn off screen as well
        # xset dpms force off
        killall insomnia_i
        killall insomnia
		exit
		;;
	-i | --interactive) # command line interactive tool
		insomnia_i
		exit
		;;
	*)
		echo "Usage: [-t | --time] [-f | --forever] [-q | --quit] [-i | --interactive]"
		exit	
		;;
esac
